---
- name: debug module
  hosts: localhost
  vars:
    fruit: "apple"
  tasks:
    - name: debug
      ansible.builtin.debug:
        var: fruit
    - name: debug msg
      ansible.builtin.debug:
        msg: "our fruit is {{ fruit }}"
        verbosity: 2