---
- name: get_url module demo
  hosts: localhost
  become: false
  vars:
    myurl: "https://releases.ansible.com/ansible/ansible-1.2.1.tar.gz"
    mydest: "/home/bogdan"
  tasks:
    - name: download file
      ansible.builtin.get_url:
        url: "{{ myurl }}"    
        dest: "{{ mydest }}"
        mode: '644'
        owner: bogdan
        group: bogdan