- name: line in file
  hosts: localhost
  # become: bogdan
  tasks:
  - name: add
    lineinfile:
      path: /home/bogdan/ansible-bog/lineinfile.txt
      line: "html_directory = no"
      state: present
      backup: yes
      # delegate_to: 127.0.0.1